version: '3.8'

services:
  backend:
    build: ./python-bot
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./python-bot:/app

  frontend:
    build: ./chat-app
    ports:
      - "4200:80"
    depends_on:
      - backend